# Generated by Django 2.2.8 on 2020-04-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('fname', models.CharField(max_length=25, verbose_name='first name')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('lname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('birtday', models.DateField(verbose_name='Дата рождения')),
                ('passport', models.CharField(choices=[('1', 'ID'), ('2', 'AN'), ('3', 'AC')], max_length=2)),
                ('number_pass', models.CharField(max_length=20, unique=True)),
                ('body_pass', models.CharField(max_length=3)),
                ('pin', models.CharField(max_length=6)),
                ('file', models.FileField(default='media/None/no-img.jpg', upload_to='media/')),
                ('role', models.CharField(choices=[('1', 'Инструктор'), ('2', 'Координатор'), ('3', 'Регистратор')], max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
