# Generated by Django 2.2.12 on 2020-04-29 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0003_auto_20200426_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='body_pass',
            field=models.TextField(error_messages={'invalid': 'Неправильный номер '}, max_length=15, validators=[django.core.validators.RegexValidator(regex='[A-Z]+$')], verbose_name='Орган, который дал паспорт'),
        ),
        migrations.AlterField(
            model_name='man',
            name='number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона без пробела'),
        ),
        migrations.AlterField(
            model_name='man',
            name='number_pass',
            field=models.CharField(max_length=7, unique=True, verbose_name='Номер паспорта'),
        ),
    ]
