# Generated by Django 2.2.12 on 2020-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_auto_20200429_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='body_pass',
            field=models.CharField(max_length=15, verbose_name='Орган, который дал паспорт'),
        ),
    ]
