# Generated by Django 2.2.12 on 2020-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_auto_20200518_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/', verbose_name='QR code'),
        ),
    ]
